# References:
# - Dependabot yml file based on 'directory' example found at:
#   GitHub (no date) [online] Configuration options for the dependabot.yml file.
#   Available at: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file (Accessed: 27 June 2023)
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of directory which contains requirements.txt
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions" # Location of directory which contains GitHub workflows
    schedule:
      interval: "weekly"
