# Generated by Django 4.2.2 on 2023-06-08 11:51

import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('django_db_logger', '0002_auto_20190109_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStatusLog',
            fields=[
                ('statuslog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_db_logger.statuslog')),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'user log entry',
                'verbose_name_plural': 'user log entries',
                'ordering': ('-create_datetime',),
            },
            bases=('django_db_logger.statuslog',),
        ),
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'verbose_name': 'admin log entry',
                'verbose_name_plural': 'admin log entries',
                'ordering': ['-action_time'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
