name: Django CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Run Tests with Coverage and Generate Report
        run: |
          coverage run --source='.' manage.py test
          coverage html

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: htmlcov

  deploy:
    name: Deploy
    needs: test
    environment: fierce-refuge-23993
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
