# References:
# - Building python package based on 'Python Starter Workflow' found at:
#   GitHub (no date) [online] Building and testing Python.
#   Available at: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python (Accessed: 27 June 2023).
#
# - Coverage steps based on 'Integration with coverage.py' found at:
#   Django (no date) [online] Django: Advanced testing topics.
#   Available at: https://docs.djangoproject.com/en/4.2/topics/testing/advanced/ (Accessed: 27 June 2023).
#
# - Upload test report steps based on 'Publishing code coverage result as a workflow artifact' section found at:
#   Edreira, D. (2021) [online] Create a GitHub Actions CI pipeline for a Python Package.
#   Available at: https://dedreira.medium.com/create-a-github-actions-ci-pipeline-for-a-python-package-4c4c02dc5f2e (Accessed: 27 June 2023).
#
# - Deploy push event conditional is based on 'Example usage of the github context' found at:
#   Github (no date) [online] Contexts, GitHub Docs.
#   Available at: https://ghdocs-prod.azurewebsites.net/en/actions/learn-github-actions/contexts (Accessed: 29 June 2023).
name: Django CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Migrations and Collect Static Files
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Tests with Coverage and Generate Report
        run: |
          coverage run --source='.' manage.py test
          coverage html

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: htmlcov

  deploy:
    name: Deploy
    needs: test
    if: ${{ github.event_name == 'push' }}
    environment: fierce-refuge-23993

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Migrations and Collect Static Files
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
